version: "3"

services:
  android:
    volumes:
# don't mount directly to the home directory of scummvm user in the container
# because that will override setting its ownership to scummvm:scummvm
# The mounting points are all created with owner root
      - /home/antoniou/scummvm-android:/home/scummvm/.android
      - /home/antoniou/Workspace/scummvm:/data/sharedrepo
    entrypoint: /bin/bash

