version: "3"

services:
  android:
    volumes:
# don't mount directly to the home directory of scummvm user in the container
# because that will override setting its ownership to scummvm:scummvm
# The mounting points are all created with owner root
      - /your-local-path-here-to-android-folder-for-keys-and-licenses:/home/scummvm/.android
      - /your-locel-path-here-to-your-copy-of-scummvm-repository:/data/sharedrepo
    entrypoint: /bin/bash

